_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_pafpn_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  FPN:
    NORM: "GN"
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ANCHOR_GENERATOR:
    ANGLES: [[0, 30, 60, 90]]
  RPN:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
  ROI_HEADS:
    NAME: "RROIHeads"
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 10.0)
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "projects/PANet/output"