_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    ANGLES: [[0, 30, 60]]
    SIZES : [[32], [64], [128], [256], [512]]
  RPN:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
  ROI_HEADS:
    NAME: "CascadeRROIHeads"
    NUM_CLASSES: 16
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    CLS_AGNOSTIC_BBOX_REG: True
DATASETS:
  TRAIN: ("dota1.5_train",)
  TEST: ("dota1.5_val",)
SOLVER:
  BASE_LR: 0.003
  CHECKPOINT_PERIOD: 18000
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (800, 1000, 1200)
  DETECTIONS_PER_IMAGE: 1000
  EVAL_PERIOD: 18000
OUTPUT_DIR: "projects/PANet/output/dota1.5/cascade_frcnnR50_rotated"
