_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    ANGLES: [[0, 30, 60]]
    SIZES : [[32], [64], [128], [256], [512]]
  RPN:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
  ROI_HEADS:
    NAME: "RROIHeads"
    NUM_CLASSES: 16
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 10.0)
DATASETS:
  TRAIN: ("dota1.5_train",)
  TEST: ("dota1.5_val",)
SOLVER:
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 27000
  STEPS: (210000, 250000)
  MAX_ITER: 270000
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (800, 1000)
  DETECTIONS_PER_IMAGE: 1000
  EVAL_PERIOD: 27000
OUTPUT_DIR: "projects/PANet/output/dota1.5/frcnnR50_rotated"
