_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "RRPN"
  ANCHOR_GENERATOR:
    NAME: "RotatedAnchorGenerator"
    ANGLES: [[0, 30, 60, 90]]
    SIZES : [[8, 16, 32, 64]]
  RPN:
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
  ROI_HEADS:
    NAME: "RROIHeads"
    NUM_CLASSES: 16
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignRotated"
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 10.0)
DATASETS:
  TRAIN: ("dota1.5_train",)
  TEST: ("dota1.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 1000
  EVAL_PERIOD: 5000
OUTPUT_DIR: "projects/PANet/output"
