_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES : [[8, 16, 32, 64, 128]]
  ROI_HEADS:
    NUM_CLASSES: 15
    NMS_THRESH_TEST: 0.6
DATASETS:
  TRAIN: ("isaid_train",)
  TEST: ("isaid_val",)
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (400, 600, 800, 1000, 1200)
  DETECTIONS_PER_IMAGE: 1000
  EVAL_PERIOD: 5000
OUTPUT_DIR: "projects/PANet/output/isaid_exp_logs/mrcnnR50_isaid"
