_BASE_: "Base-SiameseMaskRCNN-Fast-C4.yaml"
MODEL:
  WEIGHTS: "/media/ashwin/DATA/detectron2/output1/model_0000999.pth"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("xView2_train",)
  TEST: ("xView2_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (6, 8)
  MAX_ITER: 10
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)