_BASE_: "Base-SiameseRCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("xView2_train",)
  TEST: ("xView2_val",)
SOLVER:
  #STEPS: (6000, 8000)
  #MAX_ITER: 12000
  CHECKPOINT_PERIOD: 1000
OUTPUT_DIR: "/media/ashwin/DATA/detectron/projects/SiameseMaskRCNN/"
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 200
